# Generated by Django 5.0.1 on 2024-01-30 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_photos_photo_task_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='task',
        ),
    ]
